/**
 * @module partner-settlement/partnerLedgerEngine
 * @description Pure Stage-2 partner-ledger engine (no I/O). The runtime heart of the
 * partner report: classifies each certified partner-related transaction, builds the
 * Layer-A partner current accounts, derives Layer-B equalization from CERTIFIED and
 * SYMMETRIC components only, enforces the per-transaction cap, and surfaces everything
 * unprovable as UNRESOLVED (never guessed, never silently coerced).
 *
 * Boundaries honoured:
 *  - Capital is NEVER inferred from Purchase/Renovation; it requires an approved
 *    capital fact (approvedCapitalTxIds). Otherwise → LOAN_VS_CAPITAL_UNPROVEN.
 *  - A direct partner↔partner transfer with unknown purpose → TRANSFER_PURPOSE_UNKNOWN.
 *  - A custodian movement (e.g. Anastasia) is uncertified custody, not a partner loan.
 *  - Each source transaction contributes to Layer A XOR Layer B — never both
 *    (non-double-count, verified by withinPerTransactionCap at runtime).
 *  - Unknown = null, never 0.
 */

import type { NormalizedPartnerTx } from './ledgerRowFilter'
import {
  classifyTransactionRole, classifyPartnerFunding, classifyTransferPurpose,
  type ClassifierTxn,
} from './classifyPartnerTransaction'
import { withinPerTransactionCap, isEqualizationSymmetric } from './invariants'
import { equalizationHeadline, symmetryResidual, roundEur, type Headline } from './partnerReportBFormulas'
import { resolvePartnerSplit, type PartnerSplit } from './ownershipRules'
import type {
  PartnerAccountComponent, PartnerCurrentAccount, PartnerTxClass,
  ClassificationSummaryRow, PartnerPropertyPosition, UnresolvedItem,
} from './partnerReportBTypes'

const PARTNERS = ['Yossi', 'Jacob'] as const
type Partner = typeof PARTNERS[number]

// ─── Per-line classification ─────────────────────────────────────────────────────

export interface ClassifiedLine {
  readonly id: string
  readonly date: string
  readonly propertyName: string | null
  readonly category: string
  readonly subcategory: string | null
  readonly amountEur: number
  readonly klass: PartnerTxClass
  /** partner this line's Layer-A claim attaches to (null when not a Layer-A line) */
  readonly partner: Partner | null
  /** signed Layer-A contribution to CA_partner (JJ owes partner = +) */
  readonly layerAClaim: number
  /** inter-partner Layer-B claim magnitude generated by this line (capital only) */
  readonly layerBClaim: number
  readonly certified: boolean
  readonly capOk: boolean
  readonly unresolved: UnresolvedItem | null
}

function toClassifierTxn(tx: NormalizedPartnerTx, hasApprovedCapitalFact: boolean): ClassifierTxn {
  return {
    category: tx.category,
    subcategory: tx.subcategory,
    payerRole: tx.payer.role,
    payerName: tx.payer.canonical,
    payeeRole: tx.payee.role,
    payeeName: tx.payee.canonical,
    hasApprovedCapitalFact,
  }
}

/** Known, certifiable direct-transfer purposes derived from the canonical subcategory. */
function transferPurposeFromSubcat(sub: string | null): 'reimbursable_loan' | 'reimbursement' | 'UNKNOWN' {
  if (sub === 'Partner Loan') return 'reimbursable_loan'
  if (sub === 'Expense Reimbursement') return 'reimbursement'
  return 'UNKNOWN' // 'Transfer', 'Cash Withdrawal', 'Owner Payment', null, ...
}

function unresolved(kind: UnresolvedItem['kind'], tx: NormalizedPartnerTx, reason: string): UnresolvedItem {
  return {
    kind,
    ref: `${tx.date} · ${tx.category}/${tx.subcategory ?? '—'} · ${tx.payer.canonical ?? tx.payer.raw ?? '?'}→${tx.payee.canonical ?? tx.payee.raw ?? '?'}`,
    reason,
    amountEur: tx.amountEur,
    sourceRef: { system: 'public.transactions', ref: tx.id },
  }
}

/**
 * Classify a single normalized partner transaction into its economic role and the
 * signed Layer-A / Layer-B claims it generates. Pure and total.
 */
export function classifyLine(
  tx: NormalizedPartnerTx,
  opts: { approvedCapitalTxIds?: ReadonlySet<string>; split?: PartnerSplit } = {},
): ClassifiedLine {
  const A = tx.amountEur
  const base = {
    id: tx.id, date: tx.date, propertyName: tx.propertyName,
    category: tx.category, subcategory: tx.subcategory, amountEur: A,
  }
  const done = (
    klass: PartnerTxClass, partner: Partner | null, layerAClaim: number,
    layerBClaim: number, certified: boolean, u: UnresolvedItem | null,
  ): ClassifiedLine => ({
    ...base, klass, partner, layerAClaim, layerBClaim, certified,
    capOk: withinPerTransactionCap(A, layerAClaim, layerBClaim),
    unresolved: u,
  })

  const payer = tx.payer, payee = tx.payee
  const payerPartner = payer.role === 'PARTNER'
  const payeePartner = payee.role === 'PARTNER'

  // Custodian involved → uncertified cash custody (never a partner loan). 12b.
  if (payer.custodian || payee.custodian) {
    return done('CUSTODIAN_MOVEMENT', null, 0, 0, false,
      unresolved('CUSTODIAN_SETTLEMENT_UNCERTIFIED', tx,
        'movement to/from a cash custodian — not a partner account; settlement uncertified'))
  }

  // Identity ambiguity in a settlement-sensitive role → UNRESOLVED, never guessed.
  // (A partner is present, but the counterparty is a non-empty name we cannot map
  //  confidently, in a Transfer/JJ context where mis-resolution would change the class.)
  if ((payerPartner || payeePartner)) {
    const other = payerPartner ? payee : payer
    const ambiguous = other.role === 'EXTERNAL' && !other.confident && (other.raw ?? '').trim() !== ''
    if (ambiguous && tx.category === 'Transfer') {
      return done('UNRESOLVED', null, 0, 0, false,
        unresolved('IDENTITY_UNRESOLVED', tx,
          `counterparty "${other.raw}" could not be resolved to a partner/JJ/custodian in a Transfer`))
    }
  }

  const role = classifyTransactionRole(toClassifierTxn(tx, false))

  // Direct partner↔partner transfer — purpose-gated.
  if (role === 'DIRECT_PARTNER_TRANSFER') {
    const purpose = transferPurposeFromSubcat(tx.subcategory)
    if (purpose === 'UNKNOWN') {
      void classifyTransferPurpose(toClassifierTxn(tx, false)) // canonical helper (→ UNKNOWN)
      return done('DIRECT_PARTNER_TRANSFER', null, 0, 0, false,
        unresolved('TRANSFER_PURPOSE_UNKNOWN', tx,
          'direct partner↔partner transfer with no certified settlement purpose'))
    }
    // Known purpose: a certifiable inter-partner balance movement (settlement, NOT
    // profit). Payer partner pays payee partner → payee owes payer. Expressed as a
    // signed Layer-B net (Jacob-owes-Yossi positive when Yossi is the payer/lender).
    const jacobOwesYossi = (payer.canonical as Partner) === 'Yossi' ? A : -A
    return {
      ...base, klass: 'DIRECT_PARTNER_TRANSFER', partner: null, layerAClaim: 0,
      layerBClaim: jacobOwesYossi, certified: true,
      capOk: withinPerTransactionCap(A, 0, jacobOwesYossi), unresolved: null,
    }
  }

  // Partner-funded expense / partner→JJ contribution.
  if (role === 'PARTNER_FUNDED_EXPENSE' || role === 'PARTNER_TO_JJ') {
    const hasApprovedCapital = opts.approvedCapitalTxIds?.has(tx.id) ?? false
    const funding = classifyPartnerFunding(toClassifierTxn(tx, hasApprovedCapital))
    const partner = payer.canonical as Partner
    if (funding === 'REIMBURSABLE_LOAN') {
      return done('REIMBURSABLE_LOAN', partner, A, 0, true, null) // JJ owes partner +A
    }
    if (funding === 'CAPITAL') {
      // Capital: allocate to Layer B via ownership split. Certified only if the split
      // is confirmed/estimated; otherwise the property ownership blocks it.
      const split = opts.split
      const otherWhole = partner === 'Yossi' ? split?.jacob : split?.yossi
      if (split && otherWhole != null && split.confidence !== 'pending_verification') {
        const claim = A * otherWhole // other partner owes contributor
        // signed Jacob-owes-Yossi
        const jacobOwesYossi = partner === 'Yossi' ? claim : -claim
        return { ...base, klass: 'CAPITAL', partner: null, layerAClaim: 0,
          layerBClaim: jacobOwesYossi, certified: true,
          capOk: withinPerTransactionCap(A, 0, jacobOwesYossi), unresolved: null }
      }
      return done('CAPITAL', null, 0, 0, false,
        unresolved('OWNERSHIP_PENDING', tx, 'capital contribution but property ownership split not confirmed'))
    }
    // UNRESOLVED (Purchase/Renovation without an approved capital fact)
    return done('UNRESOLVED', null, 0, 0, false,
      unresolved('LOAN_VS_CAPITAL_UNPROVEN', tx,
        'partner-funded Purchase/Renovation with no approved capital fact — loan vs capital unprovable'))
  }

  // JJ → partner: reimbursement / withdrawal / distribution. As a CA cash movement it
  // reduces what JJ owes the partner (certified debit), regardless of exact sub-purpose.
  if (role === 'JJ_TO_PARTNER') {
    const partner = payee.canonical as Partner
    return done('JJ_TO_PARTNER', partner, -A, 0, true, null)
  }

  // Partner personally collected income owed to JJ → holds JJ's money; needs onward
  // settlement proof to certify. Surface, do not silently count.
  if (role === 'INCOME_COLLECTED_BY_PARTNER') {
    return done('INCOME_COLLECTED_BY_PARTNER', null, 0, 0, false,
      unresolved('OTHER', tx, 'income personally collected by a partner — onward settlement to JJ not certified'))
  }

  return done('EXTERNAL_OR_OTHER', null, 0, 0, false, null)
}

// ─── Layer A aggregation ─────────────────────────────────────────────────────────

export interface PartnerLedgerOptions {
  readonly approvedCapitalTxIds?: ReadonlySet<string>
  /** resolves a whole-property Yossi/Jacob split for a property (capital allocation) */
  readonly splitFor?: (propertyName: string | null) => PartnerSplit
}

export interface PartnerLedgerResult {
  readonly lines: readonly ClassifiedLine[]
  readonly partnerAccounts: readonly PartnerCurrentAccount[]
  readonly classificationSummary: readonly ClassificationSummaryRow[]
  readonly partnerPositionsByProperty: ReadonlyMap<string, PartnerPropertyPosition[]>
  readonly interPartnerTransferNetEur: number // signed Jacob-owes-Yossi from certified direct transfers
  readonly capitalEqualizationNetEur: number  // signed Jacob-owes-Yossi from certified capital
  readonly capViolations: number
  readonly unresolved: readonly UnresolvedItem[]
}

const COMPONENT_LABEL: Record<PartnerTxClass, string> = {
  REIMBURSABLE_LOAN: 'Reimbursable expenses funded (JJ owes partner)',
  CAPITAL: 'Approved capital contribution',
  JJ_TO_PARTNER: 'Paid by JJ to partner (reimbursement/withdrawal/distribution)',
  PARTNER_TO_JJ: 'Cash contributed to JJ',
  INCOME_COLLECTED_BY_PARTNER: 'Income personally collected',
  DIRECT_PARTNER_TRANSFER: 'Direct partner transfer',
  CUSTODIAN_MOVEMENT: 'Custodian movement',
  UNRESOLVED: 'Unresolved',
  EXTERNAL_OR_OTHER: 'External / other',
}

export function buildPartnerLedger(
  txns: readonly NormalizedPartnerTx[],
  opts: PartnerLedgerOptions = {},
): PartnerLedgerResult {
  const lines: ClassifiedLine[] = []
  const unresolvedItems: UnresolvedItem[] = []
  let capViolations = 0
  let interPartnerTransferNet = 0
  let capitalNet = 0

  // Layer-A component accumulation: partner → class → {sum, count}
  const compByPartner = new Map<Partner, Map<PartnerTxClass, { sum: number; count: number; certified: boolean }>>()
  for (const p of PARTNERS) compByPartner.set(p, new Map())
  // per-property, per-partner certified/unresolved contribution
  const propPos = new Map<string, Map<Partner, { certified: number; unresolved: number }>>()
  const summary = new Map<PartnerTxClass, { count: number; amount: number; certified: boolean }>()

  const addProp = (name: string | null, partner: Partner, certified: number, unres: number) => {
    const key = name ?? '(no property)'
    if (!propPos.has(key)) propPos.set(key, new Map())
    const m = propPos.get(key)!
    const cur = m.get(partner) ?? { certified: 0, unresolved: 0 }
    m.set(partner, { certified: cur.certified + certified, unresolved: cur.unresolved + unres })
  }

  for (const tx of txns) {
    const split = opts.splitFor ? opts.splitFor(tx.propertyName) : undefined
    const line = classifyLine(tx, { approvedCapitalTxIds: opts.approvedCapitalTxIds, split })
    lines.push(line)

    // summary
    const s = summary.get(line.klass) ?? { count: 0, amount: 0, certified: line.certified }
    s.count += 1; s.amount += tx.amountEur; s.certified = s.certified && line.certified
    summary.set(line.klass, s)

    if (!line.capOk) {
      capViolations += 1
      unresolvedItems.push(unresolved('PER_TRANSACTION_CAP_VIOLATION', tx,
        `per-transaction cap violated: |A|=${line.layerAClaim} |B|=${line.layerBClaim} > amount ${tx.amountEur}`))
    }

    if (line.unresolved) {
      unresolvedItems.push(line.unresolved)
      if (line.partner) addProp(tx.propertyName, line.partner, 0, tx.amountEur)
      else if (tx.payer.role === 'PARTNER' && tx.payer.canonical) addProp(tx.propertyName, tx.payer.canonical as Partner, 0, tx.amountEur)
      continue
    }

    // certified Layer A
    if (line.partner && line.layerAClaim !== 0) {
      const m = compByPartner.get(line.partner)!
      const c = m.get(line.klass) ?? { sum: 0, count: 0, certified: true }
      c.sum += line.layerAClaim; c.count += 1
      m.set(line.klass, c)
      addProp(tx.propertyName, line.partner, line.layerAClaim, 0)
    }
    // certified Layer B (direct transfer / capital) — net inter-partner
    if (line.klass === 'DIRECT_PARTNER_TRANSFER' && line.certified) interPartnerTransferNet += line.layerBClaim
    if (line.klass === 'CAPITAL' && line.certified) capitalNet += line.layerBClaim
  }

  const partnerAccounts: PartnerCurrentAccount[] = PARTNERS.map(party => {
    const m = compByPartner.get(party)!
    const components: PartnerAccountComponent[] = Array.from(m.entries()).map(([klass, v]) => ({
      label: COMPONENT_LABEL[klass],
      klass,
      amountEur: roundEur(v.sum),
      count: v.count,
      certified: v.certified,
    }))
    const hasAny = components.length > 0
    const net = hasAny ? roundEur(components.reduce((a, c) => a + c.amountEur, 0)) : null
    const unresAmt = Array.from(propPos.values())
      .reduce((a, pm) => a + (pm.get(party)?.unresolved ?? 0), 0)
    return {
      party,
      ledgerBalanceEur: net,
      status: hasAny ? 'PARTIAL' : 'PENDING',
      components,
      unresolvedAmountEur: unresAmt > 0 ? roundEur(unresAmt) : null,
      explain: components.map(c => ({
        label: c.label, amountEur: c.amountEur,
        tracesTo: [{ system: 'public.transactions', note: `${c.count} certified line(s)` }],
      })),
    }
  })

  const classificationSummary: ClassificationSummaryRow[] = Array.from(summary.entries())
    .map(([klass, v]) => ({ klass, count: v.count, amountEur: roundEur(v.amount), certified: v.certified }))
    .sort((a, b) => b.count - a.count)

  const partnerPositionsByProperty = new Map<string, PartnerPropertyPosition[]>()
  Array.from(propPos.entries()).forEach(([prop, m]) => {
    partnerPositionsByProperty.set(prop, PARTNERS
      .filter(p => m.has(p))
      .map(p => ({
        party: p,
        certifiedContributionEur: roundEur(m.get(p)!.certified),
        unresolvedContributionEur: roundEur(m.get(p)!.unresolved),
      })))
  })

  return {
    lines,
    partnerAccounts,
    classificationSummary,
    partnerPositionsByProperty,
    interPartnerTransferNetEur: roundEur(interPartnerTransferNet),
    capitalEqualizationNetEur: roundEur(capitalNet),
    capViolations,
    unresolved: unresolvedItems,
  }
}

// ─── Layer B (equalization) helpers — CERTIFIED, SYMMETRIC inputs only ───────────

export interface CapitalContribution {
  readonly contributor: Partner
  readonly amountEur: number
  readonly split: PartnerSplit
}

/** EP deltas from a single capital contribution (other partner owes contributor). */
export function capitalEqualizationDelta(c: CapitalContribution): { epYossi: number; epJacob: number } {
  const otherWhole = c.contributor === 'Yossi' ? (c.split.jacob ?? 0) : (c.split.yossi ?? 0)
  const claim = c.amountEur * otherWhole // other owes contributor
  // EP_P = net owed TO partner P. Contributor is owed `claim`; other owes `claim`.
  if (c.contributor === 'Yossi') return { epYossi: +claim, epJacob: -claim }
  return { epYossi: -claim, epJacob: +claim }
}

export interface ProfitDistribution {
  readonly entitlementYossi: number
  readonly entitlementJacob: number
  readonly receivedYossi: number
  readonly receivedJacob: number
}

/** EP from a certified profit distribution: EP_P = entitlement_P − received_P. */
export function profitEqualization(d: ProfitDistribution): { epYossi: number; epJacob: number } {
  return {
    epYossi: d.entitlementYossi - d.receivedYossi,
    epJacob: d.entitlementJacob - d.receivedJacob,
  }
}

export interface HeadlineResult {
  readonly headline: Headline
  readonly epYossi: number
  readonly epJacob: number
  readonly symmetryResidual: number
  readonly symmetric: boolean
}

/**
 * Derive the debtor/creditor headline from finalized EPs. Returns symmetric=false
 * (and a null-debtor headline) when EP_Y + EP_J is not ~0, so the caller's gate keeps
 * the assertion blocked. Never asserts on asymmetric inputs.
 */
export function deriveHeadlineFromEP(epYossi: number, epJacob: number): HeadlineResult {
  const residual = symmetryResidual(epYossi, epJacob)
  const symmetric = isEqualizationSymmetric(epYossi, epJacob)
  if (!symmetric) {
    return {
      headline: { debtor: null, creditor: null, amountEur: 0 },
      epYossi, epJacob, symmetryResidual: residual, symmetric: false,
    }
  }
  const h = equalizationHeadline(epYossi, epJacob)
  return { headline: { ...h, amountEur: roundEur(h.amountEur) }, epYossi, epJacob, symmetryResidual: residual, symmetric: true }
}
