-- =============================================================================
-- m9_d_verification_tasks
-- Created: 2026-07-13
-- Author: M9-D Architecture Review (Yossi + Claude)
--
-- Purpose: Verification task queue for M9-D Source Date Verification workflow.
--   Turns "missing data" into a managed work queue with priorities and search guidance.
--
-- Architecture decisions (Yossi, 13 July 2026):
--   1. lifecycle.verification_tasks -- not a separate schema.
--      Tasks are born from lifecycle facts; they don't exist independently.
--   2. No trigger -- generate_verification_tasks() is called on demand.
--      Triggers deferred to M10 once the model is stable.
--   3. reason -- WHY the task exists (missing_date != conflicting_sources).
--      Two tasks with identical missing_field may require completely different resolution paths.
--   4. proposed_value_json JSONB -- flexible payload.
--      Today: {"date":"2023-08-15"}. Tomorrow: {"amount":50000,"currency":"EUR"}.
--      Next year: {"date":"...","confidence":"estimated"}. TEXT would break all three.
--   5. search_strategy JSONB -- not just WHERE to look, but HOW to look.
--      Array of {order, source, match} gives JHKA a complete search plan, not just a source list.
--
-- Key architectural separation:
--   pending_verification  = DATA STATE  (field on ownership_period / capital_event)
--   verification_task     = WORK STATE  (row in this table)
--   These are two separate layers. One NULL can generate one task. They evolve independently.
--
-- Rollback:
--   DROP FUNCTION IF EXISTS lifecycle.generate_verification_tasks();
--   DROP TABLE IF EXISTS lifecycle.verification_tasks;
-- =============================================================================


-- =============================================================================
-- TABLE: lifecycle.verification_tasks
-- =============================================================================

CREATE TABLE lifecycle.verification_tasks (
  id                    UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

  -- What is missing
  source_table          TEXT        NOT NULL
                        CHECK (source_table IN (
                          'ownership_period',
                          'capital_event',
                          'partner_entry',
                          'property_acquisition'
                        )),
  source_id             UUID        NOT NULL,
  -- Soft reference only. No FK -- P-ARCH-5: lifecycle schema has zero FK to any table.
  -- If the source row is voided, the task remains as historical record.

  missing_field         TEXT        NOT NULL,
  -- Examples: 'effective_from', 'effective_date', 'capital_payment', 'document_reference'

  -- Why this task exists
  reason                TEXT        NOT NULL
                        CHECK (reason IN (
                          'missing_date',
                          'missing_amount',
                          'conflicting_sources',
                          'legacy_correction',
                          'manual_review',
                          'unknown_partner_payment'
                        )),

  -- How to resolve it
  expected_source_type  TEXT        NOT NULL,
  search_strategy       JSONB,
  -- JHKA search plan: [{order: int, source: text, match: text | null}]

  -- Work management
  priority              TEXT        NOT NULL DEFAULT 'medium'
                        CHECK (priority IN ('high', 'medium', 'low')),

  status                TEXT        NOT NULL DEFAULT 'pending'
                        CHECK (status IN (
                          'pending',
                          'evidence_found',
                          'confirmed',
                          'no_source_available'
                        )),

  -- Evidence found (status = evidence_found)
  evidence_source       TEXT,
  evidence_description  TEXT,
  proposed_value_json   JSONB,

  -- Approval (status = confirmed)
  confirmed_by          TEXT,
  confirmed_at          TIMESTAMPTZ,
  notes                 TEXT,

  -- Timestamps
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Prevent duplicate tasks for the same source record + field + reason
  UNIQUE (source_id, missing_field, reason)
);

COMMENT ON TABLE lifecycle.verification_tasks IS
  'Work queue for missing or uncertain lifecycle facts. '
  'Each row = one business fact that needs verification from a source document. '
  'Architecture: pending_verification = data state; verification_task = work state. '
  'Generated by generate_verification_tasks() on demand, not by triggers (M9 phase).';

-- Indexes
CREATE INDEX idx_vtasks_status    ON lifecycle.verification_tasks (status);
CREATE INDEX idx_vtasks_priority  ON lifecycle.verification_tasks (priority);
CREATE INDEX idx_vtasks_source    ON lifecycle.verification_tasks (source_table, source_id);

-- RLS: deny-all (consistent with all lifecycle tables)
ALTER TABLE lifecycle.verification_tasks ENABLE ROW LEVEL SECURITY;


-- =============================================================================
-- FUNCTION: lifecycle.generate_verification_tasks()
-- =============================================================================

CREATE OR REPLACE FUNCTION lifecycle.generate_verification_tasks()
RETURNS TABLE (
  tasks_created  INT,
  tasks_skipped  INT,
  detail         TEXT
)
LANGUAGE plpgsql
AS $$
DECLARE
  v_created INT := 0;
  v_skipped INT := 0;
  r RECORD;
BEGIN

  -- 1. ownership_period: effective_from = NULL
  FOR r IN
    SELECT
      op.id          AS op_id,
      op.property_name,
      ei.canonical_name AS partner_name
    FROM lifecycle.ownership_period op
    JOIN lifecycle.partner_entry pe
      ON pe.property_name = op.property_name
     AND pe.entity_id     = op.entity_id
    JOIN lifecycle.entity_identity ei ON ei.id = pe.entity_id
    WHERE op.effective_from IS NULL
      AND op.effective_from_confidence = 'pending_verification'
      AND op.status != 'void'
  LOOP
    INSERT INTO lifecycle.verification_tasks (
      source_table, source_id, missing_field, reason,
      expected_source_type, search_strategy, priority
    ) VALUES (
      'ownership_period', r.op_id, 'effective_from', 'missing_date',
      'partnership_agreement',
      jsonb_build_array(
        jsonb_build_object('order', 1, 'source', 'financial_documents',
          'match', 'partnership agreement ' || r.property_name),
        jsonb_build_object('order', 2, 'source', 'email',
          'match', r.partner_name || ' ' || r.property_name),
        jsonb_build_object('order', 3, 'source', 'whatsapp',
          'match', r.partner_name || ' partnership'),
        jsonb_build_object('order', 4, 'source', 'google_drive',
          'match', r.property_name || ' agreement'),
        jsonb_build_object('order', 5, 'source', 'manual_upload', 'match', NULL)
      ),
      'high'
    )
    ON CONFLICT (source_id, missing_field, reason) DO NOTHING;
    IF FOUND THEN v_created := v_created + 1;
    ELSE          v_skipped := v_skipped + 1;
    END IF;
  END LOOP;

  -- 2. capital_event: effective_date = NULL
  FOR r IN
    SELECT
      ce.id          AS ce_id,
      ce.property_name,
      ce.amount_eur,
      ce.event_subtype,
      ei.canonical_name AS payer_name
    FROM lifecycle.capital_event ce
    JOIN lifecycle.entity_identity ei ON ei.id = ce.entity_id
    WHERE ce.effective_date IS NULL
      AND ce.effective_date_confidence = 'pending_verification'
      AND ce.status != 'void'
  LOOP
    INSERT INTO lifecycle.verification_tasks (
      source_table, source_id, missing_field, reason,
      expected_source_type, search_strategy, priority
    ) VALUES (
      'capital_event', r.ce_id, 'effective_date', 'missing_date',
      'bank_transfer',
      jsonb_build_array(
        jsonb_build_object('order', 1, 'source', 'financial_documents',
          'match', 'bank transfer ' || r.payer_name || ' ' || r.property_name),
        jsonb_build_object('order', 2, 'source', 'email',
          'match', r.payer_name || ' transfer ' || r.amount_eur::TEXT),
        jsonb_build_object('order', 3, 'source', 'whatsapp',
          'match', r.payer_name || ' ' || r.amount_eur::TEXT),
        jsonb_build_object('order', 4, 'source', 'manual_upload', 'match', NULL)
      ),
      'medium'
    )
    ON CONFLICT (source_id, missing_field, reason) DO NOTHING;
    IF FOUND THEN v_created := v_created + 1;
    ELSE          v_skipped := v_skipped + 1;
    END IF;
  END LOOP;

  -- 3. partner_entry with ZERO capital events (Oren pattern)
  FOR r IN
    SELECT
      pe.id          AS pe_id,
      pe.property_name,
      ei.canonical_name AS partner_name
    FROM lifecycle.partner_entry pe
    JOIN lifecycle.entity_identity ei ON ei.id = pe.entity_id
    WHERE pe.status != 'void'
      AND NOT EXISTS (
        SELECT 1
        FROM lifecycle.capital_event ce
        WHERE ce.entity_id    = pe.entity_id
-- m9_d_verification_tasks — Applied: 2026-07-13
-- Verification task queue for M9-D Source Date Verification workflow.
-- Architecture: pending_verification = DATA STATE; verification_task = WORK STATE
-- Rollback: DROP FUNCTION lifecycle.generate_verification_tasks(); DROP TABLE lifecycle.verification_tasks;
-- =============================================================================

CREATE TABLE lifecycle.verification_tasks (
  id                    UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  source_table          TEXT        NOT NULL
                        CHECK (source_table IN ('ownership_period','capital_event','partner_entry','property_acquisition')),
  source_id             UUID        NOT NULL,
  missing_field         TEXT        NOT NULL,
  reason                TEXT        NOT NULL
                        CHECK (reason IN ('missing_date','missing_amount','conflicting_sources','legacy_correction','manual_review','unknown_partner_payment')),
  expected_source_type  TEXT        NOT NULL,
  search_strategy       JSONB,
  priority              TEXT        NOT NULL DEFAULT 'medium'
                        CHECK (priority IN ('high', 'medium', 'low')),
  status                TEXT        NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending','evidence_found','confirmed','no_source_available')),
  evidence_source       TEXT,
  evidence_description  TEXT,
  proposed_value_json   JSONB,
  confirmed_by          TEXT,
  confirmed_at          TIMESTAMPTZ,
  notes                 TEXT,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (source_id, missing_field, reason)
);

COMMENT ON TABLE lifecycle.verification_tasks IS
  'Work queue for missing or uncertain lifecycle facts. '
  'pending_verification = data state; verification_task = work state. '
  'Generated by generate_verification_tasks() on demand (triggers deferred to M10).';

CREATE INDEX idx_vtasks_status   ON lifecycle.verification_tasks (status);
CREATE INDEX idx_vtasks_priority ON lifecycle.verification_tasks (priority);
CREATE INDEX idx_vtasks_source   ON lifecycle.verification_tasks (source_table, source_id);

ALTER TABLE lifecycle.verification_tasks ENABLE ROW LEVEL SECURITY;
-- Zero policies = service_role only. deny-all for anon/authenticated.

CREATE OR REPLACE FUNCTION lifecycle.generate_verification_tasks()
RETURNS TABLE (tasks_created INT, tasks_skipped INT, detail TEXT)
LANGUAGE plpgsql AS $$
DECLARE v_created INT := 0; v_skipped INT := 0; r RECORD;
BEGIN
  -- 1. ownership_period.effective_from = NULL (priority: HIGH)
  FOR r IN
    SELECT op.id AS op_id, op.property_name, ei.canonical_name AS partner_name
    FROM lifecycle.ownership_period op
    JOIN lifecycle.partner_entry pe ON pe.property_name = op.property_name AND pe.entity_id = op.entity_id
    JOIN lifecycle.entity_identity ei ON ei.id = pe.entity_id
    WHERE op.effective_from IS NULL AND op.effective_from_confidence = 'pending_verification' AND op.status != 'void'
  LOOP
    INSERT INTO lifecycle.verification_tasks (source_table,source_id,missing_field,reason,expected_source_type,search_strategy,priority)
    VALUES ('ownership_period',r.op_id,'effective_from','missing_date','partnership_agreement',
      jsonb_build_array(
        jsonb_build_object('order',1,'source','financial_documents','match','partnership agreement '||r.property_name),
        jsonb_build_object('order',2,'source','email','match',r.partner_name||' '||r.property_name),
        jsonb_build_object('order',3,'source','whatsapp','match',r.partner_name||' partnership'),
        jsonb_build_object('order',4,'source','google_drive','match',r.property_name||' agreement'),
        jsonb_build_object('order',5,'source','manual_upload','match',NULL)),'high')
    ON CONFLICT (source_id,missing_field,reason) DO NOTHING;
    IF FOUND THEN v_created := v_created+1; ELSE v_skipped := v_skipped+1; END IF;
  END LOOP;
  -- 2. capital_event.effective_date = NULL (priority: MEDIUM)
  FOR r IN
    SELECT ce.id AS ce_id, ce.property_name, ce.amount_eur, ei.canonical_name AS payer_name
    FROM lifecycle.capital_event ce
    JOIN lifecycle.entity_identity ei ON ei.id = ce.entity_id
    WHERE ce.effective_date IS NULL AND ce.effective_date_confidence = 'pending_verification' AND ce.status != 'void'
  LOOP
    INSERT INTO lifecycle.verification_tasks (source_table,source_id,missing_field,reason,expected_source_type,search_strategy,priority)
    VALUES ('capital_event',r.ce_id,'effective_date','missing_date','bank_transfer',
      jsonb_build_array(
        jsonb_build_object('order',1,'source','financial_documents','match','bank transfer '||r.payer_name||' '||r.property_name),
        jsonb_build_object('order',2,'source','email','match',r.payer_name||' transfer '||r.amount_eur::TEXT),
        jsonb_build_object('order',3,'source','whatsapp','match',r.payer_name||' '||r.amount_eur::TEXT),
        jsonb_build_object('order',4,'source','manual_upload','match',NULL)),'medium')
    ON CONFLICT (source_id,missing_field,reason) DO NOTHING;
    IF FOUND THEN v_created := v_created+1; ELSE v_skipped := v_skipped+1; END IF;
  END LOOP;
  -- 3. partner_entry with zero capital_event rows (Oren pattern, priority: HIGH)
  FOR r IN
    SELECT pe.id AS pe_id, pe.property_name, ei.canonical_name AS partner_name
    FROM lifecycle.partner_entry pe
    JOIN lifecycle.entity_identity ei ON ei.id = pe.entity_id
    WHERE pe.status != 'void'
      AND NOT EXISTS (SELECT 1 FROM lifecycle.capital_event ce WHERE ce.entity_id=pe.entity_id AND ce.property_name=pe.property_name AND ce.event_subtype='partner_entry_payment' AND ce.status!='void')
  LOOP
    INSERT INTO lifecycle.verification_tasks (source_table,source_id,missing_field,reason,expected_source_type,search_strategy,priority)
    VALUES ('partner_entry',r.pe_id,'capital_payment','unknown_partner_payment','bank_transfer',
      jsonb_build_array(
        jsonb_build_object('order',1,'source','financial_documents','match','bank transfer '||r.partner_name||' '||r.property_name),
        jsonb_build_object('order',2,'source','email','match',r.partner_name||' payment '||r.property_name),
        jsonb_build_object('order',3,'source','whatsapp','match',r.partner_name||' paid'),
        jsonb_build_object('order',4,'source','manual_upload','match',NULL)),'high')
    ON CONFLICT (source_id,missing_field,reason) DO NOTHING;
    IF FOUND THEN v_created := v_created+1; ELSE v_skipped := v_skipped+1; END IF;
  END LOOP;
  RETURN QUERY SELECT v_created, v_skipped,
    'Scan complete. Tasks created: '||v_created||'. Tasks already existed (skipped): '||v_skipped||'.' AS detail;
END;
$$;

COMMENT ON FUNCTION lifecycle.generate_verification_tasks() IS
  'On-demand scanner: creates verification_tasks for all pending lifecycle facts. '
  'Idempotent. Covers: (1) ownership_period.effective_from=NULL, '
  '(2) capital_event.effective_date=NULL, (3) partner_entry with no capital_events. '
  'Usage: SELECT * FROM lifecycle.generate_verification_tasks();';
